version: '3.9'

services:
  db:
    image: postgres
    container_name: product-database
    restart: always
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  product:
    image: product
    restart: always
    container_name: product-app
    env_file:
      - ./configs/env.yaml
    ports:
      - "8000:8001"
