version: '3.9'

services:
  db:
    image: postgres
    container_name: product-database
    restart: always
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  product:
    image: product
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    container_name: product-app
    env_file:
      - ./configs/env.yaml
    ports:
      - "8081:8080"
